# Generated by Django 4.2.4 on 2023-12-05 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_productimage_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
