# Generated by Django 4.2.4 on 2023-12-19 13:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_remove_order_count_remove_order_product_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderdetail",
            old_name="quantity",
            new_name="count",
        ),
    ]
