# Generated by Django 4.2.4 on 2023-12-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_rename_quantity_orderdetail_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
